train_path: ../data/processed/gse183635_tep_tpm_train_clustered.parquet
test_path: ../data/processed/gse183635_tep_tpm_test_clustered.parquet
class_group_col: Class_group
patient_group_col: Patient_group
nonmalignant_label: nonMalignant
malignant_label: Malignant
model_name: multiclass_clustered_final
model_version: v0.1.0
use_pca: false
var_quantile: 0.15
selector_on_log: false
pca_var_threshold: 0.9
max_pca_components: null
clf_name: rf
clf_params: {}
malignant_weight: 6.0
weighting_strategy: sample_weight
class_weight_override: null
cv_splits: 8
min_cancer_recall_for_threshold: 0.9
threshold_objective: specificity
experiment_name: gse183635_multiclass_clustered
tracking_uri: null
save_local_bundle: true
save_plots: true
mlflow_log_artifacts: true
mlflow_log_model: true
output_models_dir: models
output_figures_dir: reports/figures/multiclass_clustered
random_state: 42
cluster_col: nm_cluster
