train_path: ../data/processed/gse183635_tep_tpm_train.parquet
test_path: ../data/processed/gse183635_tep_tpm_test.parquet
label_col: Class_group
positive_label: Malignant
model_name: logreg_binary
model_version: v0.1.0
use_pca: true
var_quantile: 0.2
selector_on_log: false
pca_var_threshold: 0.9
max_pca_components: null
pos_weight: 1.0
C: 1.0
max_iter: 2000
random_state: 42
cv_splits: 5
min_recall_for_threshold: 0.95
experiment_name: gse183635_binary
tracking_uri: null
save_local_bundle: true
output_models_dir: models
output_figures_dir: reports/figures/binary
n_train: 1880
n_test: 471
n_features_input: 5440
